spring:
  application:
    name: department
  data:
    mongodb:
      uri: mongodb://root:abcd1234@ds133041.mlab.com:33041/tap_stories

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
#feign:
#  hystrix:
#    enabled: false
#backend:
#  ribbon:
#    eureka:
#      enabled: false
#    client:
#       enabled: true
#    ServerListRefreshInterval: 5000

#hystrix.command.BackendCall.execution.isolation.thread.timeoutInMilliseconds: 5000
#hystrix.threadpool.BackendCallThread.coreSize: 5

#server:
#  port: 8888
##  ssl:
##    key-store: classpath:server.jks
##    key-store-password: password
##    key-password: password
#
#security.basic.enabled: false
#
## Configuration of a local Git-repo for development locally without Docker
## note that we are still using git; We just access the git-repo via file: protocol
#spring.cloud.config.server.git.uri: https://gitlab.com/microsms/microsms-config.git
#spring.cloud.config.server.git.username: coderdaudat
#spring.cloud.config.server.git.password: 027288578
##spring.cloud.config.server.native.search-locations: classpath:/config
##spring.cloud.config.server.git.uri: file:///${PWD}/../../../../microsms-config/
#
#eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
#
#spring.rabbitmq:
#  host: localhost
#  port: 5672
#
#logging:
#  level:
#    root: WARN
#    se.callista: INFO
#
#    org.springframework.amqp.rabbit.listener.BlockingQueueConsumer: INFO
#    org.apache.catalina.session.ManagerBase: INFO
#
#    # Set INFO to see the allocated port
#    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
#    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO
#
#
#
